FROM python:3.6.3-slim as tarkin_build
RUN mkdir /tarkin
WORKDIR /tarkin

RUN apt-get update && apt-get install -y build-essential
COPY requirements.txt /tarkin/requirements.txt
COPY src /tarkin/src
COPY dist /tarkin/dist

RUN ["sh", "-c", "pip install -r /tarkin/requirements.txt"]

FROM python:3.6.3-slim

COPY --from=tarkin_build /tarkin /tarkin
COPY --from=tarkin_build /root/.cache /root/.cache
WORKDIR /tarkin
COPY requirements.txt /tarkin/requirements.txt
RUN pip install -r /tarkin/requirements.txt
RUN ["sh", "-c", "pip install dist/*.tar.gz"]

RUN python -m spacy download en
RUN rm -rf /root/.cache

ENV PYTHONPATH=src/
ENTRYPOINT python src/check.py
